---
name: my workflow

on:
    workflow_dispatch:
jobs: 
      building :
        runs-on: ubuntu-latest
        steps:
        - run: echo "Hello there"
      test:
        needs: building
        runs-on: ubuntu-latest
        steps: 
          - run: echo "test successfull!!!"   