---
name: Exercise-1

on: 
    workflow_dispatch:

jobs:
     learning:
         runs-on: ubuntu-latest
         steps:
            - name: pull request
              run: echo "manual workflow run!! worked"
