---
name: Exercise-1

on: 
    pull_request:
        branches: 
              - test


jobs:
     learning:
         runs-on: ubuntu-latest
         steps:
            - name: pull request
              run: echo "pull request on certain branch!! worked"
